"""
READ-ONLY audit of the live workbook: is the sheet actually consuming the
MarketData tab, or is column L still static glyphs written by the tool?

Writes nothing. Opens the spreadsheet, lists its tabs, and reports whether
the marker column holds formulas or values.

Run: python tests/one-offs/thinking/live-sheet-audit/audit.py
"""

import json
from pathlib import Path

CONFIG = Path.home() / ".ed_capi_config.json"


def main() -> int:
    if not CONFIG.exists():
        print(f"No config at {CONFIG}; pass a sheet id another way.")
        return 2
    sheet_id = json.loads(CONFIG.read_text()).get("sheet_id")
    if not sheet_id:
        print("Config has no sheet_id.")
        return 2

    from APITool.google import GoogleSheetsExporter

    exporter = GoogleSheetsExporter()
    book = exporter.open_spreadsheet(sheet_id)

    titles = [ws.title for ws in book.worksheets()]
    print(f"Spreadsheet: {book.title}")
    print(f"Tabs ({len(titles)}):")
    for t in titles:
        mark = ("  <-- generated by us"
                if t in ("FreighterData", "MarketData", "ShipCargo") else "")
        print(f"    {t}{mark}")
    print()
    print("MarketData tab present:", "MarketData" in titles)

    totals = book.worksheet("Totals Tab")

    # Ask for FORMULAS, not computed values. This is the whole question:
    # a formula means the sheet renders it itself; a bare glyph means the
    # tool wrote the picture.
    formulas = totals.get("L1:L30", value_render_option="FORMULA")
    values = totals.get("L1:L30", value_render_option="FORMATTED_VALUE")

    print()
    print("Column L, rows 1-30  (formula | rendered):")
    for i in range(30):
        f = (formulas[i][0] if i < len(formulas) and formulas[i] else "")
        v = (values[i][0] if i < len(values) and values[i] else "")
        if not f and not v:
            continue
        flag = "FORMULA" if str(f).startswith("=") else "static "
        print(f"  L{i+1:<3} [{flag}] {str(f)[:70]!r}  ->  {str(v)[:20]!r}")

    any_formula = any(
        str(row[0]).startswith("=") for row in formulas if row and row[0]
    )
    print()
    print("VERDICT:", "column L is FORMULA-DRIVEN" if any_formula
          else "column L holds STATIC values written by the tool")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
