"""
Where things are on a sheet, discovered rather than assumed.

Generic spreadsheet mechanics: a layout describes which columns hold what, and
headers are found by text so moving a column needs no code change.
"""

from __future__ import annotations

from dataclasses import dataclass, field, replace
from typing import Optional, Protocol, Sequence

from .a1 import CellRange, column_to_index, index_to_column
from .guard import WriteGuard

# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------

SIGN_POSITIVE = "positive"
SIGN_NEGATIVE = "negative"


@dataclass(frozen=True)
class SheetLayout:
    """
    Where things live in the tracking spreadsheet.

    Defaults match the measured live layout (2026-09-08): headers on row 3,
    commodity rows from 5, "Left to buy" in column G, column L empty.

    ``need_sign`` supports the planned merge of "Left to buy" and "Extra next
    rnd" into a single signed column: with ``SIGN_NEGATIVE`` a value of -229
    means "buy 229" and +40 means "40 spare".
    """

    totals_tab: str = "Totals Tab"
    cargo_tab: str = "FreighterData"
    header_row: int = 3
    first_data_row: int = 5
    name_column: str = "B"
    name_header: str = "ALL SETTLEMENTS"
    need_header: str = "Left to buy"
    need_sign: str = SIGN_POSITIVE
    marker_column: str = "L"
    marker_header: str = "At Current Station"
    system_cell: str = "C2"
    station_cell: str = "G2"
    max_scan_row: int = 400
    # Overridable glyphs; see the MARKER_* constants for the alternatives.
    markers: Optional[dict] = None

    def marker_map(self) -> Optional[dict]:
        """Glyph overrides for the renderer, or None for its defaults."""
        return self.markers

    @property
    def name_column_index(self) -> int:
        return column_to_index(self.name_column)

    @property
    def marker_column_index(self) -> int:
        return column_to_index(self.marker_column)

    def marker_range(self, last_row: int) -> str:
        return f"{self.marker_column}{self.first_data_row}:{self.marker_column}{last_row}"

    def marker_header_cell(self) -> str:
        return f"{self.marker_column}{self.header_row}"

    def guard(self) -> WriteGuard:
        """The only writes this tool is ever permitted to make."""
        return WriteGuard.build(
            {
                self.totals_tab: [
                    self.system_cell,
                    self.station_cell,
                    # The marker column, header row downward. Nothing else.
                    f"{self.marker_column}{self.header_row}:{self.marker_column}",
                ],
                # FreighterData is fully generated by this tool; a whole-tab
                # rewrite there is the existing, intended behaviour.
                self.cargo_tab: ["A1:Z1000"],
            }
        )


# ---------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------

class WorksheetLike(Protocol):
    """The slice of gspread's Worksheet this module needs."""

    def get_values(self, range_name: str, **kwargs) -> list[list[str]]: ...
    def batch_update(self, data: list[dict], **kwargs): ...


class SheetLayoutError(Exception):
    """The sheet does not look the way the configuration says it should."""


def parse_quantity(raw: object) -> Optional[int]:
    """
    Parse a quantity as the sheet renders it.

    Sheets returns display strings, so thousands separators and currency-ish
    decoration are normal: '1,716' -> 1716. Returns None for blanks and for
    error values -- a formula mid-recalculation shows '#N/A', and treating
    that as zero would silently drop a real requirement.
    """
    text = str(raw).strip()
    if not text or text.startswith("#"):
        return None
    text = text.replace(",", "").replace(" ", "").replace(" ", "")
    if text in ("-", "--", "—"):
        return None
    try:
        return int(round(float(text)))
    except ValueError:
        return None

